name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish
        uses: dart-lang/setup-dart@v1
        run: |
          pub get
          dart pub publish --force